"""Package the modular viewer as one directly-openable HTML file.

No JS toolchain is required. Local ES modules are embedded as data URLs in
an import map; Three.js remains pinned to its CDN version. Gradio uses the
same builder so its source cannot drift from the standalone export.

    python -m streetview_to_3d.visualise.build_viewer
    python -m streetview_to_3d.visualise.build_viewer --check
"""
import argparse
import base64
import json
import re
from pathlib import Path

SOURCE = Path(__file__).with_name("viewer_src")
OUTPUT = Path(__file__).with_name("viewer.html")


def build_document(config: dict | None = None) -> str:
    imports = {
        "three": "https://unpkg.com/three@0.178.0/build/three.module.js",
        "three/addons/": "https://unpkg.com/three@0.178.0/examples/jsm/",
    }
    for source in sorted(SOURCE.glob("*.js")):
        encoded = base64.b64encode(source.read_bytes()).decode("ascii")
        imports[f"@viewer/{source.stem}"] = f"data:text/javascript;base64,{encoded}"
    template = (SOURCE / "template.html").read_text(encoding="utf-8")
    template = template.replace("<!-- SCENE_MANAGER -->", (SOURCE / "scene-manager.html").read_text(encoding="utf-8"))
    config_json = json.dumps(config or {}).replace("<", "\\u003c")
    template, count = re.subn(
        r'(<script id="viewer-config" type="application/json">)\s*\{\}\s*(</script>)',
        lambda match: match[1] + config_json + match[2],
        template,
    )
    if count != 1:
        raise ValueError("Expected one viewer-config element in template.html")
    return "<!-- Generated by python -m streetview_to_3d.visualise.build_viewer; edit viewer_src/ instead. -->\n" + template.replace(
        "/* VIEWER_STYLES */", (SOURCE / "styles.css").read_text(encoding="utf-8")
    ).replace("/* VIEWER_IMPORTS */", json.dumps({"imports": imports}))


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if viewer.html is stale")
    args = parser.parse_args()
    document = build_document()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != document:
            raise SystemExit("viewer.html is stale. Run python -m streetview_to_3d.visualise.build_viewer")
        print("viewer.html matches its modular source")
    else:
        OUTPUT.write_text(document, encoding="utf-8")
        print(f"Built {OUTPUT}")


if __name__ == "__main__":
    main()
